### PR TITLE
Server/fix blacklists

### LINKED ISSUE #50: Fix route for POST/blacklists
When a site gets POSTed to blacklist, check if site exists in DB, if it does not then add it in websites table, then add to blacklists table.

### PR DESCRIPTION
**Pull request by riztaha**
`run npm db:reset
`

start server
`npm run local` in server directory

visit http://localhost:9000/api/user/test
change line 119 in userRoutes.js as you wish

test in psql with 
`SELECT blacklists.id as blacklists_id, user_id, website_id, hostname, name, category
        FROM blacklists
        JOIN websites ON website_id = websites.id
        WHERE user_id = 1;`

### CODE REVIEW

File: server/helpers/dbHelper.js [hunk 1]
```diff
@@ -110,8 +110,11 @@ module.exports = (db) => {
       .query(
         `
         INSERT INTO blacklists (user_id, website_id)
-        VALUES ($1, $2)
+        SELECT $1, $2
```
Comment (jpqy) [inline server/helpers/dbHelper.js]: Not sure why lines 113-115 are here. With the unique constraint you added you can just replace these lines with `VALUES ($1, $2)` and the db will return an error if you try to insert duplicate values.

File: server/routes/userRoutes.js [hunk 2]
```diff
@@ -106,18 +93,56 @@ module.exports = (db) => {
...
+          // Capitalizes first letter of hostname
+          const name = remSuffix.charAt(0).toUpperCase() + remSuffix.slice(1);
+          const category = null;
+          dbHelper
+          .addWebsite(host_name, name, category)
+          .then((site) => {
+            dbHelper.addWebsiteToBlacklist(userId, site.id);
+          });
+        }
+        dbHelper.addWebsiteToBlacklist(userId, site.id);
```
Comment (jpqy) [inline server/routes/userRoutes.js]: This (line 109) needs to be put into an `else` block (as part of the `if (!site)`), otherwise line 106 and 109 will both run.

File: server/routes/userRoutes.js [hunk 3]
```diff
@@ -106,18 +93,56 @@ module.exports = (db) => {
...
+          // Capitalizes first letter of hostname
+          const name = remSuffix.charAt(0).toUpperCase() + remSuffix.slice(1);
+          const category = null;
+          dbHelper.addWebsite(host_name, name, category).then((site) => {
+            console.log("=====> Adding a new site to blacklist");
+            console.log(site);
+            dbHelper.addWebsiteToBlacklist(userId, site.id);
+          });
+        }
+        console.log("=====> Website exists in database");
```
Comment (jpqy) [inline server/routes/userRoutes.js]: 137-142 also need to be in the `else` block if you want a working test.

File: server/routes/userRoutes.js [hunk 4]
```diff
@@ -106,18 +93,56 @@ module.exports = (db) => {
...
+          const category = null;
+          dbHelper
+          .addWebsite(host_name, name, category)
+          .then((site) => {
+            dbHelper.addWebsiteToBlacklist(userId, site.id);
+          });
+        }
+        dbHelper.addWebsiteToBlacklist(userId, site.id);
+      })
       .catch((err) => res.json(err));
```
Comment (jpqy) [inline server/routes/userRoutes.js]: you need to send back a 4xx status code, 400 is "bad request" so use that. Change all these to `res.status(400).json(err)`

File: server/routes/userRoutes.js [hunk 5]
```diff
@@ -106,18 +93,56 @@ module.exports = (db) => {
...
+          const name = remSuffix.charAt(0).toUpperCase() + remSuffix.slice(1);
+          const category = null;
+          dbHelper.addWebsite(host_name, name, category).then((site) => {
+            console.log("=====> Adding a new site to blacklist");
+            console.log(site);
+            dbHelper.addWebsiteToBlacklist(userId, site.id);
+          });
+        }
+        console.log("=====> Website exists in database");
+        dbHelper.addWebsiteToBlacklist(userId, site.id);
```
Comment (jpqy) [inline server/routes/userRoutes.js]: You need to add `return` here to continue to `.then`

File: server/routes/userRoutes.js [hunk 6]
```diff
@@ -106,18 +93,56 @@ module.exports = (db) => {
...
+        console.log("=====> Adding an old site to this user's blacklist");
+      })
+      .then(() => res.send(`${host_name} added to blacklist`))
+      .catch((err) => res.json(err));
```
Comment (jpqy) [inline server/routes/userRoutes.js]: add `.status`

**Review by jpqy — CHANGES_REQUESTED** [review]
Left inline comments (I hope I did it correctly)

File: server/helpers/dbHelper.js (hunk 1 above)
Comment (riztaha) [reply server/helpers/dbHelper.js]: Yea this Query can revert back to what it was before. I was just testing to see diff methods of achieving the same goal. It's essentially better to have the constraint on the table instead of in queries.

File: server/routes/userRoutes.js (hunk 2 above)
Comment (riztaha) [reply server/routes/userRoutes.js]: I had it previously to if(!site.id), which made line 109 implicit that site.id is truthy

File: server/routes/userRoutes.js (hunk 4 above)
Comment (riztaha) [reply server/routes/userRoutes.js]: Fixed it on my end now

File: server/routes/userRoutes.js (hunk 3 above)
Comment (riztaha) [reply server/routes/userRoutes.js]: Fixed on my end

File: server/routes/userRoutes.js (hunk 6 above)
Comment (riztaha) [reply server/routes/userRoutes.js]: Done

File: server/routes/userRoutes.js (hunk 5 above)
Comment (riztaha) [reply server/routes/userRoutes.js]: Done

**Comment by riztaha** [comment]
Changes pushed according to jpqy's review

File: server/routes/userRoutes.js [hunk 7]
```diff
@@ -106,18 +93,57 @@ module.exports = (db) => {
...
+      .then((site) => {
+        if (!site) {
+          // Removes '.com' from end of hostname for DB.
+          const remSuffix = host_name.split(".")[0];
+          // Capitalizes first letter of hostname
+          const name = remSuffix.charAt(0).toUpperCase() + remSuffix.slice(1);
+          const category = null;
+          // Creating the website in the database before it can be added to their blacklist
+          dbHelper.addWebsite(host_name, name, category).then((site) => {
+            dbHelper.addWebsiteToBlacklist(userId, site.id);
```
Comment (jpqy) [inline server/routes/userRoutes.js]: Line 105 and 108 (and all routes in general) need to end in a response being sent back to the client, either a success message or an error message if the db operation failed. Add `.then(blacklist=>res.status(201).json(blacklist))` and a `.catch(err=>res.status(500).json(err)`
201 = created
500 = server error (db error)

I think if you leave out the .status it defaults to a success status so it's important to set the status during a failure.

**Review by jpqy — DISMISSED** [review]
Need to send back a response to client in routes

File: server/routes/userRoutes.js (hunk 2 above)
Comment (xynyx) [reply server/routes/userRoutes.js]: Your function to remove the suffix actually takes the www and capitalizes it - you want index 1 to get the actual host name.

Comment (xynyx) [reply server/routes/userRoutes.js]: Actually, I think that would depend on how it was sent from the client - like how we want to handle websites that are typed www.google.com, or google.com, or http:// etc

File: server/routes/userRoutes.js [hunk 8]
```diff
@@ -106,18 +93,63 @@ module.exports = (db) => {
...
+          .addWebsite(host_name, name, category)
+          .then((site) => {
+            dbHelper
+              .addWebsiteToBlacklist(userId, site.id)
+              .then((blacklist) => res.status(201).json(blacklist))
+              .catch((err) => res.status(500).json(err));
+          });
+        } else {
+          dbHelper
+            .addWebsiteToBlacklist(userId, site.id)
```
Comment (jpqy) [inline server/routes/userRoutes.js:114]: One last thing... a `.catch` is not provided for line 104 so if `.addWebsite` fails on line 105, the error will be uncaught. Here you can change promise nesting to promise chaining by prefixing `return` to line 107, and then moving lines 109 and 110 to the end of line 111 (remove the semicolon). Now the `.catch` on line 110 will catch both for both `.addWebsite` and `.addWebsiteToBlacklist`

**Review by jpqy — CHANGES_REQUESTED** [review]
Potential unhandled promise rejection

File: server/routes/userRoutes.js (hunk 2 above)
Comment (jpqy) [reply server/routes/userRoutes.js]: @riztaha has it correct... we are storing urls as google.com, no subdomains

File: server/routes/userRoutes.js (hunk 8 above)
Comment (riztaha) [reply server/routes/userRoutes.js:114]: Good catch, pun intended 😉

**Review by jpqy — APPROVED** [review]

File: server/helpers/dataProcessor.js [hunk 9]
```diff
@@ -26,4 +27,17 @@ const processTimeToMins = function (obj, dataObj, dataArr) {
...
+  const name = remSuffix.charAt(0).toUpperCase() + remSuffix.slice(1);
+  return name;
+};
+
+// Helper function to remove "www." if a host_name has it
+const remPrefix = function (host_name) {
+  return host_name.split("www.").join("");
+};
+
+module.exports = { compileData, extractNameFromURL, remPrefix };
```
Comment (xynyx) [inline server/helpers/dataProcessor.js:43]: Minor thing but if you don't plan to call remPrefix on it's own, you don't actually need to export it here and can just export extractNameFromURL

**Review by xynyx — APPROVED** [review]

File: server/routes/userRoutes.js [hunk 10]
```diff
@@ -95,29 +84,71 @@ module.exports = (db) => {
...
+      .catch((err) => res.status(400).json(err));
   });
 
+  // When a user wants to add a site to their blacklist
   router.post("/blacklists", (req, res) => {
     const userId = req.session.userId;
     if (!userId) {
       return res.status(403).send("A user must be signed in!");
     }
     const { host_name } = req.body.params;
```
Comment (jpqy) [inline server/routes/userRoutes.js]: Should just be `req.body`. `.param`s is for extracting `:variables` from the url

**Review by jpqy — CHANGES_REQUESTED** [review]
Bug in req.body

File: server/routes/userRoutes.js (hunk 10 above)
Comment (riztaha) [reply server/routes/userRoutes.js]: Good catch! Fixed error.

**Review by jpqy — APPROVED** [review]
